<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-D26R0D6" ignored="0" name="Default test" tests="2" failures="2" timestamp="27 Apr 2021 08:19:20 GMT" time="0.6" errors="0">
  <testcase name="loadDashboard" time="0.565" classname="Tests.LoadDashboardAPI">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Tests.LoadDashboardAPI.loadDashboard(LoadDashboardAPI.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loadDashboard -->
  <testcase name="loadDashboard" time="0.586" classname="Tests.LoadDashboardAPI">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: loadDashboard([Parameter{index=0, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=5, type=int, declaredAnnotations=[]}, Parameter{index=6, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.Object, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer)41728,(java.lang.Integer)3,null,(java.lang.String)2021-01-06T22:35:46.0327652-07:00,(java.lang.String)2021-02-3T22:35:46.0327652-07:00,(java.util.LinkedHashMap){IsSuccess=false, Message=Method called with invalid parameters.},(java.lang.String)Second]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: loadDashboard([Parameter{index=0, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=5, type=int, declaredAnnotations=[]}, Parameter{index=6, type=java.util.Map, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.Object, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer)41728,(java.lang.Integer)3,null,(java.lang.String)2021-01-06T22:35:46.0327652-07:00,(java.lang.String)2021-02-3T22:35:46.0327652-07:00,(java.util.LinkedHashMap){IsSuccess=false, Message=Method called with invalid parameters.},(java.lang.String)Second]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- loadDashboard -->
</testsuite> <!-- Default test -->
